# Generated by Django 4.1.13 on 2024-03-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bande_fluctuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('devise', models.CharField(max_length=15)),
                ('Bid', models.FloatField()),
                ('Ask', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Cours_revaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('devise', models.CharField(max_length=15)),
                ('cours', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_operation', models.DateField()),
                ('date_validation', models.DateField()),
                ('conterpartie', models.CharField(max_length=50)),
                ('devise_achat', models.CharField(max_length=5)),
                ('devise_vente', models.CharField(max_length=5)),
                ('cours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('montant_achat', models.DecimalField(decimal_places=2, max_digits=20)),
                ('montant_vendu', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('type', models.CharField(max_length=20)),
                ('direction', models.CharField(max_length=10)),
            ],
        ),
    ]
