# Generated by Django 4.1.13 on 2024-03-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='direction',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='operation',
            name='montant_vendu',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
