# Generated by Django 5.0.2 on 2024-03-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=10)),
                ('date_operation', models.DateField()),
                ('date_validation', models.DateField()),
                ('conterpartie', models.CharField(max_length=50)),
                ('devise_achat', models.CharField(max_length=5)),
                ('devise_vente', models.CharField(max_length=5)),
                ('cours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('montant_achat', models.DecimalField(decimal_places=2, max_digits=20)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
    ]
