# Generated by Django 4.2.8 on 2024-03-14 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_operation_ref'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bande_fluctuation',
            old_name='max',
            new_name='Ask',
        ),
        migrations.RenameField(
            model_name='bande_fluctuation',
            old_name='min',
            new_name='Bid',
        ),
    ]
