# Generated by Django 5.0.6 on 2024-05-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_sessionstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionstatus',
            name='end_jour',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionstatus',
            name='start_jour',
            field=models.DateField(blank=True, null=True),
        ),
    ]
