# Generated by Django 5.0.2 on 2024-05-14 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_sessionstatus_end_jour_sessionstatus_start_jour'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Journee',
        ),
    ]
