# Generated by Django 5.0.2 on 2024-05-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_delete_journee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modev', models.CharField(max_length=10)),
                ('nooper', models.CharField(max_length=100)),
                ('datoper', models.DateField()),
                ('devisec', models.CharField(max_length=10)),
                ('devised', models.CharField(max_length=10)),
                ('mntdevd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('mntdevc', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cours12', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nomd', models.CharField(max_length=100)),
                ('libelle', models.CharField(max_length=200)),
                ('client', models.CharField(max_length=100)),
                ('comptec', models.CharField(max_length=100)),
                ('agence', models.CharField(max_length=100)),
            ],
        ),
    ]
