# Generated by Django 5.0.2 on 2024-05-28 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_position_wallet_rename_transaction_operationcorp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
