# Generated by Django 5.0.2 on 2024-05-28 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_delete_position_delete_wallet'),
    ]

    operations = [
    ]
