# Generated by Django 5.0.6 on 2024-06-06 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_limitescontreparties_operation_limite_contrepartie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='limite_contrepartie',
        ),
        migrations.DeleteModel(
            name='LimitesContreparties',
        ),
    ]
