# Generated by Django 5.0.6 on 2024-06-06 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_operation_limite_contrepartie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitesContreparties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrepartie', models.CharField(max_length=50)),
                ('Ligne_48h', models.BooleanField(default=False)),
                ('limite', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='operation',
            name='limite',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='app.limitescontreparties'),
        ),
    ]
