# Generated by Django 5.0.6 on 2024-06-06 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_operation_limite'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LimitesContreparties',
            new_name='LimiteContrepartie',
        ),
    ]
