# Generated by Django 5.0.6 on 2024-06-06 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_limitescontreparties_limitecontrepartie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='limitecontrepartie',
            old_name='contrepartie',
            new_name='conterpartie',
        ),
    ]
