# Generated by Django 5.0.6 on 2024-06-06 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_contrepartie_limitecontrepartie_conterpartie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='limite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='app.limitecontrepartie'),
        ),
    ]
