# Generated by Django 5.0.6 on 2024-06-19 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_delete_test_alter_limitecontrepartie_limite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionStatus',
        ),
    ]
